spring:
  profiles:
    active: 
    - dev
---
spring:
  profiles: dev
  application: 
     name: microservicecloud-config-nuc-dev
---
spring:
  profiles: test
  application:
      name: microservicecloud-config-nuc-test    
